---
abstract: 'Displays Gravatar images within RT'
author:
  - 'Christian Loos <cloos@netsandbox.de>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-Gravatar
no_index:
  directory:
    - html
    - inc
  package:
    - RT::User
requires:
  Crypt::SSLeay: 0
  Digest::MD5: 0
  LWP::UserAgent: 0
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/cloos/RT-Extension-Gravatar
version: 1.01
x_module_install_rtx_version: 0.36
x_requires_rt: 4.0.0
x_rt_too_new: 4.4.0
